export  const LOGIN_WEB="REGISTER_USER";
export const REGISTER_USER="REGISTER_USER";
export const GET_KIND_PRODUCT="GET_KIND_PRODUCT";
export const GET_MATERIAL_PRODUCT="GET_MATERIAL_PRODUCT";
export const GET_USERS= "GET_USERS";
export const GET_USERS_CURRENT= "GET_USERS_CURRENT";
export const DELETE_USER="DELETE_USER";
export const UP_LOAD_FILE ="UP_LOAD_FILE";
// Product
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_PRODUCT= "GET_PRODUCT";
export const DELETE_PRODUCT= "DELETE_PRODUCT";
export const VIEW_DETAIL_PRODUCT= "VIEW_DETAIL_PRODUCT";
export const UPDATE_PRODUCT= "UPDATE_PRODUCT";
export const GET_KIND_RAITING= "GET_KIND_RAITING";
export const GET_NEW_ITEM="GET_NEW_ITEM"
// Chart
export const COUNT_RAITING="COUNT_RAITING"
export const GET_REVIEW ="GET_REVIEW"
export const SEND_REVIEW_USER="SEND_REVIEW_USER";
//cart
export const ADD_TO_CART="ADD_TO_CART";
export const UPDATE_CART="UPDATE_CART";
export const DELETE_PRODUCT_IN_CART="DELETE_PRODUCT_IN_CART"